---

- name: Configure RBAC for BIGIP API
  hosts: "{{ target }}"
  gather_facts: no
  serial: 1
  connection: local
  vars:
    user_bigip_token: "{{ user_login_result.json.token.token }}"
    bigip_token: "{{ login_result.json.token.token }}"
    resource_id: "{{ resource_group_result.json.id }}"
    provider_id: "{{ provider_result.json['items'][0]['id'] }}"
    user_id: "{{ provider_user_result.json['items'][0]['id'] }}" 
    
  tasks:
    # Login to BigIP and retreive token ID
  - name: Login to BigIP as user {{account_name}}
    no_log: True
    #debugger: always
    uri:
      url: https://{{ ansible_host }}/mgmt/shared/authn/login
      method: POST
      body: 
        username: "{{ account_name }}"
        password: "{{ account_password }}"
        loginProviderName: "tmos"
      return_content: yes
      validate_certs: no
      status_code: 200
      timeout: 30
      body_format: json
    register: user_login_result
    retries: 30
    delay: 10
    until: user_login_result.status is defined and user_login_result.status == 200
    changed_when: false

  - name: GET virtual servers to create user in API users
    uri:
      url: https://{{ ansible_host }}/mgmt/tm/ltm/virtual
      method: GET
      return_content: yes
      headers:
          X-F5-Auth-Token: "{{ user_bigip_token }}"
      validate_certs: no
      status_code: 200, 202
      timeout: 30
      body_format: json
    register: user_api_result
    retries: 10
    delay: 60
    until: 
    - user_api_result.status is defined
    - user_api_result.status != 503

  # Logout From BigIP to prevent too many active session (Max 100 is allowed by TMOS)
  - name: Logout from bigIP
    uri:
      url: https://{{ ansible_host }}/mgmt/shared/authz/tokens/{{ user_bigip_token }}
      method: DELETE
      headers:
          X-F5-Auth-Token: "{{ user_bigip_token }}"
      validate_certs: no
      status_code: 200
      timeout: 30
      body_format: json

##################################################################################
  - name: Login to BigIP
    no_log: True
    #debugger: always
    uri:
      url: https://{{ ansible_host }}/mgmt/shared/authn/login
      method: POST
      body: 
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        loginProviderName: "tmos"
      return_content: yes
      validate_certs: no
      status_code: 200
      timeout: 30
      body_format: json
    register: login_result
    retries: 30
    delay: 10
    until: login_result.status is defined and login_result.status == 200
    changed_when: false

  # update token timeout to 1 hour
  - name: update timeout to 1H
    uri:
      url: https://{{ ansible_host }}/mgmt/shared/authz/tokens/{{ bigip_token }}
      method: PATCH
      headers:
          X-F5-Auth-Token: "{{ bigip_token }}"
      body: '{"timeout":"3600"}'
      validate_certs: no
      status_code: 200
      timeout: 30
      body_format: json

  - name: GET authentication provider ID
    uri:
      url: https://{{ ansible_host }}/mgmt/cm/system/authn/providers/tmos?$select=id
      method: GET
      return_content: yes
      headers:
          X-F5-Auth-Token: "{{ bigip_token }}"
      validate_certs: no
      status_code: 200, 202
      timeout: 30
      body_format: json
    register: provider_result
    retries: 10
    delay: 60
    until: 
    - provider_result.status is defined
    - provider_result.status != 503

  - name: GET  user ID in authentication provider
    uri:
      url: https://{{ ansible_host }}/mgmt/cm/system/authn/providers/tmos/{{provider_id}}/users?$filter=name+eq+{{account_name}}&$select=id
      method: GET
      return_content: yes
      headers:
          X-F5-Auth-Token: "{{ bigip_token }}"
      validate_certs: no
      status_code: 200, 202
      timeout: 30
      body_format: json
    register: provider_user_result
    retries: 10
    delay: 60
    until: 
    - provider_user_result.status is defined
    - provider_user_result.status != 503

  - name: GET Resource Role iControl_REST_API_User
    uri:
      url: https://{{ ansible_host }}/mgmt/shared/authz/roles/iControl_REST_API_User
      method: GET
      return_content: yes
      headers:
          X-F5-Auth-Token: "{{ bigip_token }}"
      validate_certs: no
      status_code: 200, 202
      timeout: 30
      body_format: json
    register: api_user_result
    retries: 10
    delay: 60
    until: 
    - api_user_result.status is defined
    - api_user_result.status != 503

  - name: UPDATE Resource Role iControl_REST_API_User
    uri:
      url: https://{{ ansible_host }}/mgmt/shared/authz/roles/iControl_REST_API_User
      method: PUT
      return_content: yes
      headers:
          X-F5-Auth-Token: "{{ bigip_token }}"
      body: 
        userReferences: "{{ api_user_result.json.userReferences | rejectattr('link', 'equalto', 'https://localhost/mgmt/cm/system/authn/providers/tmos/' + provider_id + '/users/' + user_id) }}"
        resourceGroupReferences: "{{ api_user_result.json.resourceGroupReferences }}"
        name: "{{ api_user_result.json.name }}"
      validate_certs: no
      status_code: 200, 202
      timeout: 30
      body_format: json
    register: api_user_patch_result
    retries: 10
    delay: 60
    until: 
    - api_user_patch_result.status is defined
    - api_user_patch_result.status != 503

  - name: Create resource group
    uri:
      url: https://{{ ansible_host }}/mgmt/shared/authz/resource-groups
      method: POST
      return_content: yes
      headers:
          X-F5-Auth-Token: "{{ bigip_token }}"
      body: 
        name: hrzResourceGroup
        resources:
        - restMethod: GET
          resourceMask: /mgmt/tm/ltm/profile/client-ssl
        - restMethod: POST
          resourceMask: /mgmt/tm/ltm/profile/client-ssl
        - restMethod: PATCH
          resourceMask: /mgmt/tm/ltm/profile/client-ssl/**
        - restMethod: GET
          resourceMask: /mgmt/tm/sys/file/ssl-cert/**
        - restMethod: DELETE
          resourceMask: /mgmt/tm/sys/file/ssl-cert/**
        - restMethod: DELETE
          resourceMask: /mgmt/tm/sys/file/ssl-key/**
        - restMethod: POST
          resourceMask: /mgmt/shared/file-transfer/uploads/**
        - restMethod: POST
          resourceMask: /mgmt/tm/sys/crypto/**
      validate_certs: no
      status_code: 200, 202
      timeout: 30
      body_format: json
    register: resource_group_result
    retries: 10
    delay: 60
    until: 
    - resource_group_result.status is defined
    - resource_group_result.status != 503

  - name: Create role
    uri:
      url: https://{{ ansible_host }}/mgmt/shared/authz/roles
      method: POST
      return_content: yes
      headers:
          X-F5-Auth-Token: "{{ bigip_token }}"
      body: 
        name: '{{account_name}}_role'
        userReferences:
            - link: "{{ 'https://localhost/mgmt/shared/authz/users/' + account_name }}"
        resourceGroupReferences:
            - link: https://localhost/mgmt/shared/authz/resource-groups/{{resource_id}}
      validate_certs: no
      status_code: 200, 202
      timeout: 30
      body_format: json
    register: role_result
    retries: 10
    delay: 60
    until: 
    - role_result.status is defined
    - role_result.status != 503

  # Logout From BigIP to prevent too many active session (Max 100 is allowed by TMOS)
  - name: Logout from bigIP
    uri:
      url: https://{{ ansible_host }}/mgmt/shared/authz/tokens/{{ bigip_token }}
      method: DELETE
      headers:
          X-F5-Auth-Token: "{{ bigip_token }}"
      validate_certs: no
      status_code: 200
      timeout: 30
      body_format: json
